### PR TITLE
discord-0.0.8 add desktop menu entry

### PR DESCRIPTION
**Pull request by mahnmut**
Add a desktop menu entry for wm with icon and description.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Hi. Good you found how to fix the manifest thing. I tried your ebuild changes and it ends up giving a .desktop file called "discord-discord.desktop". This does not seem right?

File: /usr/share/applications/discord-discord.desktop

**Comment by anders-larsson** [comment]
I'm off to bed. I'll merge it tomorrow if I don't have any additional opinions.

**Comment by mahnmut** [comment]
Apparently normal according to my teamspeak3-teamspeak-client-bin.desktop
In the wm menu it's appear as exepted.

Maybe there is a better solution.

And yeah forgot the manifest the first time.

**Comment by anders-larsson** [comment]
Please rebase your commit into one unified commit. Once that's done I'm a happy person.

**Pull request closed without merging**
